import type { SectionType, SectionContentMap } from '@/lib/types';
import {
  DEMO_HERO, DEMO_BRAND_STATEMENT, DEMO_SERVICES, DEMO_EVENTS,
  DEMO_PORTFOLIO, DEMO_TESTIMONIALS, DEMO_FAQ, DEMO_STATS,
  DEMO_PROCESS, DEMO_TEXT_IMAGE, DEMO_CTA,
  DEMO_EDITORIAL_LIST, DEMO_CINEMATIC_IMAGE, DEMO_TEAM_MEMBERS, DEMO_IMAGE_CAROUSEL,
  DEMO_PORTFOLIO_FILTERED_GALLERY, DEMO_PORTFOLIO_FEATURED,
} from '@/demo/sectionPreviews';

export interface SectionVariant {
  id: string;
  label: string;
  description: string;
}

export interface SectionTypeConfig {
  type: SectionType;
  label: string;
  description: string;
  group: 'featured' | 'content' | 'conversion';
  icon: string;
  variants: SectionVariant[];
  defaultVariant: string;
  defaultContent: SectionContentMap[SectionType];
  previewContent: SectionContentMap[SectionType];
}

function uid(): string {
  return Math.random().toString(36).slice(2, 10);
}

export const SECTION_TYPES: SectionTypeConfig[] = [
  {
    type: 'hero-carousel',
    label: 'Hero Carousel',
    description: 'Large visual introduction with slides',
    group: 'featured',
    icon: 'Image',
    variants: [
      { id: 'default', label: 'Full Width', description: 'Full-viewport hero with background images' },
    ],
    defaultVariant: 'default',
    defaultContent: {
      slides: [{
        id: uid(), image: '', mobile_image: null, image_alt: '', eyebrow: '', headline: '', highlight_word: '',
        description: '', cta_text: '', cta_url: '', secondary_cta_text: '',
        secondary_cta_url: '', focal_x: 0.5, focal_y: 0.5,
      }],
    },
    previewContent: DEMO_HERO,
  },
  {
    type: 'brand-statement',
    label: 'Brand Statement',
    description: 'Large editorial statement',
    group: 'featured',
    icon: 'Quote',
    variants: [
      { id: 'default', label: 'Editorial', description: 'Left-aligned editorial typography' },
      { id: 'centered', label: 'Centered', description: 'Centered with larger type' },
    ],
    defaultVariant: 'default',
    defaultContent: {
      eyebrow: '', primary_text: '', highlighted_text: '', description: '',
      metadata: '', accent_word: '', variant: 'default',
    },
    previewContent: DEMO_BRAND_STATEMENT,
  },
  {
    type: 'services-editorial',
    label: 'Services',
    description: 'Service showcase with images',
    group: 'content',
    icon: 'Briefcase',
    variants: [
      { id: 'default', label: 'Grid', description: '3-column card grid with images' },
      { id: 'compact', label: 'Compact', description: 'Dense grid with minimal spacing' },
    ],
    defaultVariant: 'default',
    defaultContent: { heading: '', description: '', services: [], variant: 'default' },
    previewContent: DEMO_SERVICES,
  },
  {
    type: 'events-editorial',
    label: 'Events',
    description: 'Featured events from the Events CMS',
    group: 'content',
    icon: 'Calendar',
    variants: [
      { id: 'default', label: 'Grid', description: '3-column event cards' },
      { id: 'minimal', label: 'Minimal', description: 'Clean list layout' },
    ],
    defaultVariant: 'default',
    defaultContent: { heading: '', description: '', limit: 3, featured_only: false, upcoming_only: false, variant: 'default' },
    previewContent: DEMO_EVENTS,
  },
  {
    type: 'portfolio-gallery',
    label: 'Portfolio Gallery',
    description: 'Project gallery with images',
    group: 'content',
    icon: 'LayoutGrid',
    variants: [
      { id: 'grid', label: 'Grid', description: 'Uniform grid layout' },
      { id: 'masonry', label: 'Masonry', description: 'Staggered asymmetric layout' },
      { id: 'asymmetric', label: 'Asymmetric', description: 'Editorial 12-col asymmetric layout' },
    ],
    defaultVariant: 'grid',
    defaultContent: { heading: '', description: '', items: [], variant: 'grid' },
    previewContent: DEMO_PORTFOLIO,
  },
  {
    type: 'testimonials',
    label: 'Testimonials',
    description: 'Client quotes and reviews',
    group: 'content',
    icon: 'MessageSquare',
    variants: [
      { id: 'default', label: 'Grid', description: '2-column quote grid' },
      { id: 'carousel', label: 'Carousel', description: 'Single quote carousel' },
    ],
    defaultVariant: 'default',
    defaultContent: { heading: '', description: '', testimonials: [], variant: 'default' },
    previewContent: DEMO_TESTIMONIALS,
  },
  {
    type: 'faq',
    label: 'FAQ',
    description: 'Frequently asked questions',
    group: 'content',
    icon: 'HelpCircle',
    variants: [
      { id: 'default', label: 'Accordion', description: 'Expandable question rows' },
    ],
    defaultVariant: 'default',
    defaultContent: { heading: '', description: '', items: [] },
    previewContent: DEMO_FAQ,
  },
  {
    type: 'stats',
    label: 'Stats',
    description: 'Animated number counters',
    group: 'content',
    icon: 'BarChart3',
    variants: [
      { id: 'default', label: 'Grid', description: '4-column stat counters' },
      { id: 'compact', label: 'Compact', description: 'Smaller condensed layout' },
    ],
    defaultVariant: 'default',
    defaultContent: { heading: '', stats: [], variant: 'default' },
    previewContent: DEMO_STATS,
  },
  {
    type: 'process',
    label: 'Process',
    description: 'Step-by-step process showcase',
    group: 'content',
    icon: 'ListOrdered',
    variants: [
      { id: 'default', label: 'Steps', description: 'Numbered steps grid' },
    ],
    defaultVariant: 'default',
    defaultContent: { heading: '', description: '', steps: [] },
    previewContent: DEMO_PROCESS,
  },
  {
    type: 'text-image',
    label: 'Text + Image',
    description: 'Text content with image',
    group: 'content',
    icon: 'Columns',
    variants: [
      { id: 'default', label: 'Split', description: 'Text and image side by side' },
      { id: 'split', label: 'Image Left', description: 'Image on left, text on right' },
      { id: 'centered', label: 'Centered', description: 'Centered editorial statement without image' },
    ],
    defaultVariant: 'default',
    defaultContent: { eyebrow: '', heading: '', body: '', image: '', image_alt: '', image_position: 'right', cta_text: '', cta_url: '', variant: 'default' },
    previewContent: DEMO_TEXT_IMAGE,
  },
  {
    type: 'cta',
    label: 'CTA',
    description: 'Call to action / booking',
    group: 'conversion',
    icon: 'MousePointerClick',
    variants: [
      { id: 'default', label: 'Default', description: 'Centered with background image' },
      { id: 'full-width', label: 'Full Width', description: 'Full-bleed background' },
      { id: 'minimal', label: 'Minimal', description: 'Clean text-only layout' },
    ],
    defaultVariant: 'default',
    defaultContent: { eyebrow: '', heading: '', description: '', button_text: '', button_url: '', secondary_button_text: '', secondary_button_url: '', background_image: '', variant: 'default' },
    previewContent: DEMO_CTA,
  },
  {
    type: 'editorial-list',
    label: 'Editorial List',
    description: 'Numbered editorial items with titles and descriptions',
    group: 'content',
    icon: 'ListOrdered',
    variants: [
      { id: 'default', label: 'Default', description: 'Numbered vertical list with 12-col grid layout' },
    ],
    defaultVariant: 'default',
    defaultContent: { heading: null, description: null, items: [] },
    previewContent: DEMO_EDITORIAL_LIST,
  },
  {
    type: 'cinematic-image',
    label: 'Cinematic Image',
    description: 'Full-width cinematic image with caption overlay',
    group: 'featured',
    icon: 'Film',
    variants: [
      { id: 'default', label: 'Default', description: 'Full-bleed cinematic image with gradient overlay' },
    ],
    defaultVariant: 'default',
    defaultContent: { image: '', mobile_image: null, image_alt: null, focal_x: 0.5, focal_y: 0.5, caption: null, caption_alignment: 'left' },
    previewContent: DEMO_CINEMATIC_IMAGE,
  },
  {
    type: 'team-members',
    label: 'Team Members',
    description: 'Interactive team showcase with featured image',
    group: 'content',
    icon: 'Users',
    variants: [
      { id: 'default', label: 'Default', description: 'Featured image with interactive member list' },
    ],
    defaultVariant: 'default',
    defaultContent: { heading: null, members: [] },
    previewContent: DEMO_TEAM_MEMBERS,
  },
  {
    type: 'image-carousel',
    label: 'Image Carousel',
    description: 'Horizontal scrolling image carousel',
    group: 'content',
    icon: 'GalleryHorizontal',
    variants: [
      { id: 'default', label: 'Default', description: 'Horizontal scroll with snap and navigation' },
    ],
    defaultVariant: 'default',
    defaultContent: { heading: null, description: null, images: [] },
    previewContent: DEMO_IMAGE_CAROUSEL,
  },
  {
    type: 'blocks',
    label: 'Blocks',
    description: 'Visual block editor — heading, text, image, button, spacer',
    group: 'content',
    icon: 'LayoutTemplate',
    variants: [
      { id: 'default', label: 'Default', description: '自由布局 block editor' },
    ],
    defaultVariant: 'default',
    defaultContent: { blocks: [] },
    previewContent: { blocks: [] },
  },
  {
    type: 'services-hero',
    label: 'Services Hero',
    description: 'Large heading with split layout',
    group: 'featured',
    icon: 'Image',
    variants: [{ id: 'default', label: 'Default', description: 'Two-column hero with heading and description' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'OUR SERVICES', heading: "EXCEPTIONAL SERVICES FOR UNFORGETTABLE\nEVENTS.", description: 'From concept to execution, we offer end-to-end event solutions tailored to your vision. Whatever the occasion, we make it extraordinary.', image: '', image_alt: '' },
    previewContent: { eyebrow: 'OUR SERVICES', heading: "EXCEPTIONAL SERVICES FOR UNFORGETTABLE\nEVENTS.", description: 'From concept to execution, we offer end-to-end event solutions tailored to your vision. Whatever the occasion, we make it extraordinary.', image: '', image_alt: '' },
  },
  {
    type: 'services-featured',
    label: 'Featured Services',
    description: 'Featured service with image and description',
    group: 'featured',
    icon: 'Star',
    variants: [{ id: 'default', label: 'Default', description: 'Split layout with image and description' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'WHAT WE OFFER', heading: "Experiences Crafted With\nIntentions.", description: 'Every event is unique. We listen, design, and deliver experiences that reflect your vision and exceed expectations.', image: '', label: 'EVENT PLANNING', label_text: 'Full-service event planning tailored to your vision and goals.', link_text: 'Explore Our Services' },
    previewContent: { eyebrow: 'WHAT WE OFFER', heading: "Experiences Crafted With\nIntentions.", description: 'Every event is unique. We listen, design, and deliver experiences that reflect your vision and exceed expectations.', image: '', label: 'EVENT PLANNING', label_text: 'Full-service event planning tailored to your vision and goals.', link_text: 'Explore Our Services' },
  },
  {
    type: 'services-cards',
    label: 'Services Cards',
    description: 'Eight-card service grid with images',
    group: 'content',
    icon: 'LayoutGrid',
    variants: [{ id: 'default', label: 'Default', description: 'Four-column card grid with images' }],
    defaultVariant: 'default',
    defaultContent: { cards: [] },
    previewContent: { cards: [
      { id: '1', title: 'Event Planning', description: 'Full-service planning from concept to execution.', image: '' },
      { id: '2', title: 'Event Design & Styling', description: 'Creative direction and aesthetic curation for your event.', image: '' },
      { id: '3', title: 'Weddings & Celebrations', description: 'Beautifully curated weddings and milestone celebrations.', image: '' },
      { id: '4', title: 'Corporate Events', description: 'Professional conferences, summits, and corporate gatherings.', image: '' },
      { id: '5', title: 'Production & Lighting', description: 'Stage design, sound, lighting, and full production.', image: '' },
      { id: '6', title: 'Catering & Hospitality', description: 'Premium catering and guest experience management.', image: '' },
      { id: '7', title: 'Photography & Videography', description: 'Professional coverage to capture every moment.', image: '' },
      { id: '8', title: 'Private Events', description: 'Exclusive birthday parties, anniversaries, and private gatherings.', image: '' },
    ] },
  },
  {
    type: 'services-directory',
    label: 'Service Directory',
    description: 'Complete service list in two columns',
    group: 'content',
    icon: 'List',
    variants: [{ id: 'default', label: 'Default', description: 'Two-column service rows' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'OUR FULL SERVICES', heading: "MORE EXPERIENCES.\nMORE POSSIBILITIES.", description: 'From large-scale productions to intimate gatherings, our full range of services covers every aspect of event creation and management.', left_items: [], right_items: [] },
    previewContent: { eyebrow: 'OUR FULL SERVICES', heading: "MORE EXPERIENCES.\nMORE POSSIBILITIES.", description: 'From large-scale productions to intimate gatherings, our full range of services covers every aspect of event creation and management.', left_items: [{ id: '1', number: '04', title: 'CORPORATE EVENTS' }, { id: '2', number: '05', title: 'PRIVATE EVENTS & PARTIES' }, { id: '3', number: '06', title: 'FESTIVALS & PUBLIC EVENTS' }, { id: '4', number: '07', title: 'DECORATION & BRANDING' }, { id: '5', number: '08', title: 'SOUND, LIGHTING & STAGE PRODUCTION' }, { id: '6', number: '09', title: 'DJ & MC COORDINATION' }], right_items: [{ id: '7', number: '10', title: 'PHOTOGRAPHY & VIDEOGRAPHY' }, { id: '8', number: '11', title: 'EVENT PROMOTION & SOCIAL MEDIA' }, { id: '9', number: '12', title: 'BIRTHDAYS & GRADUATIONS' }] },
  },
  {
    type: 'services-philosophy',
    label: 'Service Philosophy',
    description: 'Editorial service explanation',
    group: 'content',
    icon: 'Quote',
    variants: [{ id: 'default', label: 'Default', description: 'Split layout with gold rule' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'THE FIESTA STANDARD', heading: "EVERY EVENT\nDESERVES ITS\nOWN STORY.", body: '' },
    previewContent: { eyebrow: 'THE FIESTA STANDARD', heading: "EVERY EVENT\nDESERVES ITS\nOWN STORY.", body: "We don't believe in copying the same event twice. A wedding should feel like the people getting married. A concert should feel like the artist performing. A corporate gathering should feel like the brand behind it.\n\nOur role is to understand the idea first, then build everything around it — creative direction, planning, production, coordination, and flawless execution. Every event deserves its own story, and we are here to tell it." },
  },
  {
    type: 'services-process',
    label: 'Services Process',
    description: 'Five-stage process flow',
    group: 'content',
    icon: 'GitBranch',
    variants: [{ id: 'default', label: 'Default', description: 'Horizontal/vertical process steps' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'HOW WE BRING IT TO LIFE', heading: "FROM IDEA TO\nUNFORGETTABLE.", steps: [{ id: '1', number: '01', title: 'DISCOVER', description: 'We listen to your vision and understand the heart of what you want.' }, { id: '2', number: '02', title: 'DESIGN', description: 'We develop a creative direction that brings your idea to life.' }, { id: '3', number: '03', title: 'PLAN', description: 'Every detail is mapped out with precision and care.' }, { id: '4', number: '04', title: 'PRODUCE', description: 'We execute with expertise, coordination, and flawless timing.' }, { id: '5', number: '05', title: 'DELIVER', description: 'The final experience exceeds expectations and creates lasting memories.' }] },
    previewContent: { eyebrow: 'HOW WE BRING IT TO LIFE', heading: "FROM IDEA TO\nUNFORGETTABLE.", steps: [{ id: '1', number: '01', title: 'DISCOVER', description: 'We listen to your vision and understand the heart of what you want.' }, { id: '2', number: '02', title: 'DESIGN', description: 'We develop a creative direction that brings your idea to life.' }, { id: '3', number: '03', title: 'PLAN', description: 'Every detail is mapped out with precision and care.' }, { id: '4', number: '04', title: 'PRODUCE', description: 'We execute with expertise, coordination, and flawless timing.' }, { id: '5', number: '05', title: 'DELIVER', description: 'The final experience exceeds expectations and creates lasting memories.' }] },
  },
  {
    type: 'services-image-statement',
    label: 'Image Statement',
    description: 'Full-width image with centered text',
    group: 'featured',
    icon: 'Image',
    variants: [{ id: 'default', label: 'Default', description: 'Cinematic image with overlay text' }],
    defaultVariant: 'default',
    defaultContent: { heading: "WE TAKE CARE\nOF THE DETAILS.", description: '', image: '' },
    previewContent: { heading: "WE TAKE CARE\nOF THE DETAILS.", description: '', image: '' },
  },
  {
    type: 'services-cta',
    label: 'Services CTA',
    description: 'Final call to action',
    group: 'conversion',
    icon: 'ArrowRight',
    variants: [{ id: 'default', label: 'Default', description: 'Full-width image with CTA' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: "LET'S CREATE SOMETHING EXTRAORDINARY", heading: 'Your Vision. Our Expertise.', description: '', button_text: 'BOOK YOUR EVENT', button_url: '/contact', background_image: '' },
    previewContent: { eyebrow: "LET'S CREATE SOMETHING EXTRAORDINARY", heading: 'Your Vision. Our Expertise.', description: 'Let us help you design and execute an event that reflects your vision and creates lasting memories for every guest.', button_text: 'BOOK YOUR EVENT', button_url: '/contact', background_image: '' },
  },
  {
    type: 'about-intro',
    label: 'About Intro',
    description: 'Dark hero with heading and two images',
    group: 'featured',
    icon: 'Image',
    variants: [{ id: 'default', label: 'Default', description: 'Dark bg, text left, images right' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'ABOUT FIESTA', heading: "WE DON'T JUST\nPLAN EVENTS.\nWE CREATE\nEXPERIENCES.", body: '', image: '', image_alt: '', image2: '', image2_alt: '' },
    previewContent: { eyebrow: 'ABOUT FIESTA', heading: "WE DON'T JUST\nPLAN EVENTS.\nWE CREATE\nEXPERIENCES.", body: 'Fiesta Agency is a creative event company focused on producing unforgettable weddings, concerts, corporate experiences and private celebrations across Rwanda.', image: '', image_alt: '', image2: '', image2_alt: '' },
  },
  {
    type: 'about-story',
    label: 'About Story',
    description: 'Cream editorial story section',
    group: 'content',
    icon: 'BookOpen',
    variants: [{ id: 'default', label: 'Default', description: 'Cream bg, image top, text offset' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'OUR STORY', heading: "FROM A SINGLE IDEA\nTO A REGIONAL\nLEADER.", paragraphs: [], image: '', image_alt: '' },
    previewContent: { eyebrow: 'OUR STORY', heading: "FROM A SINGLE IDEA\nTO A REGIONAL\nLEADER.", paragraphs: ["Fiesta started with a simple belief: every gathering deserves to feel extraordinary. What began as a small event coordination effort has grown into one of Rwanda's most trusted creative event agencies.", "We've produced weddings that make people cry, concerts that make people dance until sunrise, and corporate events that inspire entire organizations. Our work speaks for itself — and our clients come back because they trust us to deliver."], image: '', image_alt: '' },
  },
  {
    type: 'about-mission',
    label: 'About Mission & Vision',
    description: 'Two-column mission and vision',
    group: 'content',
    icon: 'Quote',
    variants: [{ id: 'default', label: 'Default', description: 'White bg, mission left, vision right' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: '', heading: '', body: '' },
    previewContent: { eyebrow: 'OUR MISSION', heading: "OUR MISSION", body: 'Turn ideas into well-crafted experiences.' },
  },
  {
    type: 'about-values',
    label: 'About Values',
    description: 'Dark values grid',
    group: 'content',
    icon: 'Heart',
    variants: [{ id: 'default', label: 'Default', description: 'Dark bg, 4-column values grid' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'OUR VALUES', heading: "THE PRINCIPLES\nBEHIND OUR WORK.", values: [] },
    previewContent: { eyebrow: 'OUR VALUES', heading: "THE PRINCIPLES\nBEHIND OUR WORK.", values: [
      { id: '1', num: '01', title: 'CREATIVITY', text: 'Every event is a blank canvas. We bring fresh thinking and original ideas to every project.' },
      { id: '2', num: '02', title: 'EXCELLENCE', text: "We don't settle for average. Every detail is refined until it reaches our highest standard." },
      { id: '3', num: '03', title: 'INTEGRITY', text: 'Transparent communication, honest pricing, and genuine care for every client relationship.' },
      { id: '4', num: '04', title: 'PASSION', text: 'We love what we do. That energy translates into events that feel alive and memorable.' },
    ] },
  },
  {
    type: 'about-team',
    label: 'About Team',
    description: 'Team member grid',
    group: 'content',
    icon: 'Users',
    variants: [{ id: 'default', label: 'Default', description: 'Cream bg, 5-column team grid' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'THE TEAM', heading: "THE PEOPLE BEHIND\nTHE MAGIC.", members: [] },
    previewContent: { eyebrow: 'THE TEAM', heading: "THE PEOPLE BEHIND\nTHE MAGIC.", members: [
      { id: '1', name: 'Jean-Paul Habimana', role: 'Founder & Creative Director', image: '' },
      { id: '2', name: 'Alice Uwimana', role: 'Head of Production', image: '' },
      { id: '3', name: 'David Niyonzima', role: 'Event Coordinator', image: '' },
      { id: '4', name: 'Grace Mukamana', role: 'Design Lead', image: '' },
      { id: '5', name: 'Samuel Bizimana', role: 'Technical Director', image: '' },
    ] },
  },
  {
    type: 'about-closing',
    label: 'About Closing',
    description: 'Full-width CTA with background image',
    group: 'conversion',
    icon: 'ArrowRight',
    variants: [{ id: 'default', label: 'Default', description: 'Full-width image, dark overlay, CTA' }],
    defaultVariant: 'default',
    defaultContent: { heading: "READY TO CREATE\nSOMETHING EXTRAORDINARY?", cta_text: 'GET IN TOUCH', cta_url: '/contact', background_image: '', background_image_alt: '' },
    previewContent: { heading: "READY TO CREATE\nSOMETHING EXTRAORDINARY?", cta_text: 'GET IN TOUCH', cta_url: '/contact', background_image: '', background_image_alt: '' },
  },
  {
    type: 'events-hero',
    label: 'Events Hero',
    description: 'Events page hero with heading and image',
    group: 'featured',
    icon: 'Image',
    variants: [{ id: 'default', label: 'Default', description: 'Dark bg, text left, image right' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'OUR EVENTS', heading: "EXTRAORDINARY MOMENTS.\nALWAYS.", description: 'From intimate gatherings to large-scale productions, we design and manage events that leave lasting impressions. Every detail matters.', image: '', image_alt: '' },
    previewContent: { eyebrow: 'OUR EVENTS', heading: "EXTRAORDINARY MOMENTS.\nALWAYS.", description: 'From intimate gatherings to large-scale productions, we design and manage events that leave lasting impressions. Every detail matters.', image: '', image_alt: '' },
  },
  {
    type: 'events-cta',
    label: 'Events CTA',
    description: 'Events page call to action',
    group: 'conversion',
    icon: 'ArrowRight',
    variants: [{ id: 'default', label: 'Default', description: 'Centered CTA with description' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: "LET'S CREATE TOGETHER", heading: "YOUR EVENT DESERVES\nITS OWN STORY.", description: 'Let us help you design and execute an event that reflects your vision and creates lasting memories for every guest.', button_text: 'Book Your Event', button_url: '/contact' },
    previewContent: { eyebrow: "LET'S CREATE TOGETHER", heading: "YOUR EVENT DESERVES\nITS OWN STORY.", description: 'Let us help you design and execute an event that reflects your vision and creates lasting memories for every guest.', button_text: 'Book Your Event', button_url: '/contact' },
  },
  {
    type: 'portfolio-hero',
    label: 'Portfolio Hero',
    description: 'Portfolio page hero with heading and image',
    group: 'featured',
    icon: 'Image',
    variants: [{ id: 'default', label: 'Default', description: 'Dark bg, text left, image right' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'OUR PORTFOLIO', heading: "MEMORABLE.\nLASTING\nIMPRESSIONS.", description: 'A curated collection of our most memorable moments, from intimate celebrations to large-scale productions.', image: '', image_alt: '' },
    previewContent: { eyebrow: 'OUR PORTFOLIO', heading: "MEMORABLE.\nLASTING\nIMPRESSIONS.", description: 'A curated collection of our most memorable moments, from intimate celebrations to large-scale productions.', image: '', image_alt: '' },
  },
  {
    type: 'hww-hero',
    label: 'How We Work Hero',
    description: 'How We Work page hero',
    group: 'featured',
    icon: 'Image',
    variants: [{ id: 'default', label: 'Default', description: 'Dark bg, text left, image right' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'HOW WE WORK', heading: "A SEAMLESS PROCESS.\nEXCEPTIONAL RESULTS.", description: 'From concept to execution, we handle every detail with precision, creativity and care - so you can focus on what matters most.', image: '', image_alt: '' },
    previewContent: { eyebrow: 'HOW WE WORK', heading: "A SEAMLESS PROCESS.\nEXCEPTIONAL RESULTS.", description: 'From concept to execution, we handle every detail with precision, creativity and care - so you can focus on what matters most.', image: '', image_alt: '' },
  },
  {
    type: 'hww-intro',
    label: 'How We Work Intro',
    description: 'Introduction with image and text',
    group: 'content',
    icon: 'Columns',
    variants: [{ id: 'default', label: 'Default', description: 'Split layout with image and text' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'THE FIESTA APPROACH', heading: "FROM FIRST IDEA\nTO FINAL MOMENT.", description: 'Every great event starts with a conversation.', image: '', image_alt: '', link_text: 'View Our Services', link_url: '/services' },
    previewContent: { eyebrow: 'THE FIESTA APPROACH', heading: "FROM FIRST IDEA\nTO FINAL MOMENT.", description: 'Every great event starts with a conversation.', image: '', image_alt: '', link_text: 'View Our Services', link_url: '/services' },
  },
  {
    type: 'hww-process',
    label: 'How We Work Process',
    description: 'Five-step process flow',
    group: 'content',
    icon: 'ListOrdered',
    variants: [{ id: 'default', label: 'Default', description: 'Horizontal/vertical process steps' }],
    defaultVariant: 'default',
    defaultContent: { steps: [{ num: '01', title: 'CONSULTATION', description: 'We understand your vision, requirements and expectations.' }, { num: '02', title: 'PLANNING', description: 'We develop the concept, logistics and detailed event plan.' }, { num: '03', title: 'PREPARATION', description: 'We coordinate suppliers, production and every necessary detail.' }, { num: '04', title: 'EXECUTION', description: 'The vision becomes reality through precise coordination and execution.' }, { num: '05', title: 'FOLLOW-UP', description: 'We review the experience and ensure every detail is properly concluded.' }] },
    previewContent: { steps: [{ num: '01', title: 'CONSULTATION', description: 'We understand your vision, requirements and expectations.' }, { num: '02', title: 'PLANNING', description: 'We develop the concept, logistics and detailed event plan.' }, { num: '03', title: 'PREPARATION', description: 'We coordinate suppliers, production and every necessary detail.' }, { num: '04', title: 'EXECUTION', description: 'The vision becomes reality through precise coordination and execution.' }, { num: '05', title: 'FOLLOW-UP', description: 'We review the experience and ensure every detail is properly concluded.' }] },
  },
  {
    type: 'hww-behind',
    label: 'Behind The Scenes',
    description: 'Behind the scenes image grid',
    group: 'content',
    icon: 'Images',
    variants: [{ id: 'default', label: 'Default', description: 'Large image + two smaller images' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'BEHIND THE SCENES', heading: "BEHIND\nTHE MOMENT.", description: "It's not just about what you see.", images: [] },
    previewContent: { eyebrow: 'BEHIND THE SCENES', heading: "BEHIND\nTHE MOMENT.", description: "It's not just about what you see.", images: [] },
  },
  {
    type: 'hww-why',
    label: 'Why Fiesta',
    description: 'Principles grid',
    group: 'content',
    icon: 'Heart',
    variants: [{ id: 'default', label: 'Default', description: '4-column principles grid' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'WHY FIESTA', heading: "THE PRINCIPLES\nBEHIND OUR WORK.", principles: [{ num: '01', title: 'CREATIVITY', text: 'Fresh ideas, distinctive concepts and thoughtful details.' }, { num: '02', title: 'PRECISION', text: 'Careful planning and attention to every important detail.' }, { num: '03', title: 'COLLABORATION', text: 'Working closely with clients and partners to bring the vision together.' }, { num: '04', title: 'EXCELLENCE', text: 'A commitment to delivering memorable experiences.' }] },
    previewContent: { eyebrow: 'WHY FIESTA', heading: "THE PRINCIPLES\nBEHIND OUR WORK.", principles: [{ num: '01', title: 'CREATIVITY', text: 'Fresh ideas, distinctive concepts and thoughtful details.' }, { num: '02', title: 'PRECISION', text: 'Careful planning and attention to every important detail.' }, { num: '03', title: 'COLLABORATION', text: 'Working closely with clients and partners to bring the vision together.' }, { num: '04', title: 'EXCELLENCE', text: 'A commitment to delivering memorable experiences.' }] },
  },
  {
    type: 'hww-cta',
    label: 'How We Work CTA',
    description: 'Final call to action',
    group: 'conversion',
    icon: 'ArrowRight',
    variants: [{ id: 'default', label: 'Default', description: 'Centered CTA' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'READY TO START?', heading: "PLANNING AN EVENT?\nLET'S MAKE IT HAPPEN.", description: 'Let us help you design and execute an event that reflects your vision.', button_text: 'Get In Touch', button_url: '/contact' },
    previewContent: { eyebrow: 'READY TO START?', heading: "PLANNING AN EVENT?\nLET'S MAKE IT HAPPEN.", description: 'Let us help you design and execute an event that reflects your vision.', button_text: 'Get In Touch', button_url: '/contact' },
  },
  {
    type: 'portfolio-filtered-gallery',
    label: 'Portfolio Filtered Gallery',
    description: 'Filterable project grid with category bar',
    group: 'content',
    icon: 'LayoutGrid',
    variants: [{ id: 'default', label: 'Default', description: 'Filter bar + responsive grid' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'OUR WORK', heading: '', description: '', categories: ['ALL', 'CORPORATE', 'PRIVATE', 'WEDDINGS', 'CONCERTS', 'FESTIVALS'], max_projects: 9, variant: 'grid' },
    previewContent: DEMO_PORTFOLIO_FILTERED_GALLERY,
  },
  {
    type: 'portfolio-featured',
    label: 'Portfolio Featured',
    description: 'Featured project showcase with image and text',
    group: 'featured',
    icon: 'Star',
    variants: [{ id: 'default', label: 'Default', description: 'Split layout with image and project details' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'FEATURED PROJECT', heading: '', description: '', button_text: 'View Project', button_url: '' },
    previewContent: DEMO_PORTFOLIO_FEATURED,
  },
  {
    type: 'contact-hero',
    label: 'Contact Hero',
    description: 'Contact page hero with heading and image',
    group: 'featured',
    icon: 'Image',
    variants: [{ id: 'default', label: 'Default', description: 'Dark bg, text left, image right' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'GET IN TOUCH', heading: "LET'S MAKE\nYOUR NEXT EVENT\nEXTRAORDINARY.", description: "Whether you have a clear vision or just the beginning of an idea, we're here to help bring it to life. Let's start a conversation.", image: '', image_alt: '' },
    previewContent: { eyebrow: 'GET IN TOUCH', heading: "LET'S MAKE\nYOUR NEXT EVENT\nEXTRAORDINARY.", description: "Whether you have a clear vision or just the beginning of an idea, we're here to help bring it to life. Let's start a conversation.", image: '', image_alt: '' },
  },
  {
    type: 'contact-info',
    label: 'Contact Info',
    description: 'Contact form heading and info',
    group: 'content',
    icon: 'Info',
    variants: [{ id: 'default', label: 'Default', description: 'Contact form with info sidebar' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'CONTACT INFO', heading: "WE'D LOVE\nTO HEAR FROM YOU.", event_types: ['Wedding','Corporate Event','Private Party','Gala Dinner','Conference','Other'], email: 'hello@fiestaagency.example', phone: '+1 (555) 000-0000', address: 'Design Studio, Lagos · London · Dubai' },
    previewContent: { eyebrow: 'CONTACT INFO', heading: "WE'D LOVE\nTO HEAR FROM YOU.", event_types: ['Wedding','Corporate Event','Private Party','Gala Dinner','Conference','Other'], email: 'hello@fiestaagency.example', phone: '+1 (555) 000-0000', address: 'Design Studio, Lagos · London · Dubai' },
  },
  {
    type: 'contact-location',
    label: 'Contact Location',
    description: 'Office location with map image',
    group: 'content',
    icon: 'MapPin',
    variants: [{ id: 'default', label: 'Default', description: 'Split layout with text and map' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'VISIT US', heading: "OUR\nOFFICE.", description: "We welcome visits by appointment.", image: '', image_alt: '' },
    previewContent: { eyebrow: 'VISIT US', heading: "OUR\nOFFICE.", description: "We welcome visits by appointment.", image: '', image_alt: '' },
  },
  {
    type: 'contact-cta',
    label: 'Contact CTA',
    description: 'Contact page call to action',
    group: 'conversion',
    icon: 'ArrowRight',
    variants: [{ id: 'default', label: 'Default', description: 'Full-width image with CTA' }],
    defaultVariant: 'default',
    defaultContent: { heading: "READY TO START?\nWE'RE ALL EARS.", background_image: '', background_image_alt: '' },
    previewContent: { heading: "READY TO START?\nWE'RE ALL EARS.", background_image: '', background_image_alt: '' },
  },
  {
    type: 'legal-page',
    label: 'Legal Page',
    description: 'Privacy policy or terms & conditions page',
    group: 'content',
    icon: 'FileText',
    variants: [{ id: 'default', label: 'Default', description: 'Standard legal page layout' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'Legal', heading: '', sections: [] },
    previewContent: { eyebrow: 'Legal', heading: 'PRIVACY POLICY', sections: [{ heading: '1. Information We Collect', content: 'When you contact us...' }, { heading: '2. How We Use Your Information', content: 'We use your information to...' }] },
  },
  {
    type: 'events-featured',
    label: 'Events Featured',
    description: 'Featured event heading and description',
    group: 'content',
    icon: 'Star',
    variants: [{ id: 'default', label: 'Default', description: 'Default featured event header' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'FEATURED EVENT', heading: '', description: '' },
    previewContent: { eyebrow: 'FEATURED EVENT', heading: 'FEATURED EVENT', description: 'Our most recent highlight...' },
  },
  {
    type: 'events-filter',
    label: 'Events Filter',
    description: 'Event category filter bar',
    group: 'navigation',
    icon: 'Filter',
    variants: [{ id: 'default', label: 'Default', description: 'Horizontal filter buttons' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: '', categories: ['ALL', 'CORPORATE', 'PRIVATE', 'WEDDINGS', 'CONCERTS', 'FESTIVALS'] },
    previewContent: { eyebrow: '', categories: ['ALL', 'CORPORATE', 'PRIVATE', 'WEDDINGS', 'CONCERTS', 'FESTIVALS'] },
  },
  {
    type: 'events-upcoming',
    label: 'Events Upcoming',
    description: 'Upcoming events section heading',
    group: 'content',
    icon: 'Calendar',
    variants: [{ id: 'default', label: 'Default', description: 'Default upcoming events header' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'UPCOMING EVENTS', heading: "WHAT'S COMING UP", description: '' },
    previewContent: { eyebrow: 'UPCOMING EVENTS', heading: "WHAT'S COMING UP", description: '' },
  },
  {
    type: 'events-past',
    label: 'Events Past',
    description: 'Past events section heading',
    group: 'content',
    icon: 'Clock',
    variants: [{ id: 'default', label: 'Default', description: 'Default past events header' }],
    defaultVariant: 'default',
    defaultContent: { eyebrow: 'PAST EVENTS', heading: "MOMENTS WE'VE CREATED", description: '' },
    previewContent: { eyebrow: 'PAST EVENTS', heading: "MOMENTS WE'VE CREATED", description: '' },
  },
];

export function getSectionTypeConfig(type: SectionType): SectionTypeConfig {
  return SECTION_TYPES.find((s) => s.type === type) || SECTION_TYPES[0];
}

export function getSectionLabel(type: SectionType): string {
  return getSectionTypeConfig(type).label;
}

export function getDefaultContent<T extends SectionType>(type: T): SectionContentMap[T] {
  return { ...getSectionTypeConfig(type).defaultContent } as SectionContentMap[T];
}

export function getSectionVariants(type: SectionType): SectionVariant[] {
  return getSectionTypeConfig(type).variants;
}

export function getPreviewContent(type: SectionType): SectionContentMap[SectionType] {
  return { ...getSectionTypeConfig(type).previewContent };
}
