-- Update portfolio story content with richer editorial copy
-- Original seed had only 2 short sentences per project

UPDATE public.portfolio_projects SET story = $json$
{"paragraphs":["The brief was simple: make the room feel like the last hour of sunlight. We built the entire design around a single palette - gold, ivory, and the deep green of fresh foliage. Every element, from the linen to the lighting gel, was chosen to carry that one idea through the space.","The ceremony took place outdoors as the sun dropped below the treeline. We timed the aisle walk to the exact moment the light turned amber - not by accident, but by rehearsal. The floral arch was built in three sections, each one designed to catch the light differently as the angle shifted through the golden hour.","Over two hundred guests moved through a sequence of spaces, each one shifting in mood as the evening progressed. The cocktail area was warm and open, with low arrangements that encouraged conversation. The dining room was more composed - suspended florals at varying heights, candlelight reflected in brass, and a table plan that guided guests through a narrative rather than a seating chart.","The final dance floor felt less like a reception and more like a celebration of the night itself. We stripped back the lighting to a single warm wash, brought in a live band, and let the energy of the room carry the rest. By the time the last song ended, the guests didn't want to leave - which is the only metric we judge a wedding by."]}
$json$::jsonb
WHERE slug = 'portfolio-evening-in-gold';

UPDATE public.portfolio_projects SET story = $json$
{"paragraphs":["Three hundred guests. One palette. No color except candlelight. The client wanted an evening that felt like stepping into a photograph - monochrome, still, and completely composed. We accepted the constraint and made it the foundation of everything.","We designed the room as a single composition - table, light, sound, and movement - so that the evening read as one continuous gesture. The tables were dressed in black linen with ivory napkins, each place setting aligned to the millimeter. Sculptural white florals rose from the center of each table like quiet monuments, lit from below to cast long shadows across the ceiling.","The string quartet played from an elevated platform at the center of the room, surrounded by a shallow reflecting pool we had installed specifically for the evening. The water caught the candlelight and threw it across the walls in slow, shifting patterns - a visual metronome that set the pace of the entire event.","Dinner was served in four courses, each one timed to the music. The room didn't need decoration beyond what it already had - three hundred people in black tie, a hundred candles, and the kind of silence that only happens when every detail has been considered. By dessert, the guests had stopped noticing the design, which is exactly when you know it's working."]}
$json$::jsonb
WHERE slug = 'portfolio-modern-black-tie';

UPDATE public.portfolio_projects SET story = $json$
{"paragraphs":["The product was the story. Our job was to make the room disappear at the right moment. The client had spent two years developing what they were about to unveil, and they needed the environment to match the weight of that work - not compete with it, not distract from it, but hold it like a frame holds a painting.","We chose a converted warehouse in the industrial district, stripped it back to its concrete bones, and built the entire experience from scratch. The lighting was architectural - recessed LED strips tracing the lines of the ceiling beams, a single spotlight on the reveal stage, and everything else pulled to near-darkness. The room felt like it was holding its breath.","The choreographed reveal took four weeks to plan and twelve seconds to execute. A single cue triggered the lighting shift, the sound design, and the stage curtain drop in sequence. The product appeared in a column of white light while the soundtrack - composed specifically for the moment - filled the room from speakers hidden in the walls. The audience didn't applaud immediately. They waited. That pause told us everything.","Three hundred guests experienced an evening that moved from anticipation to revelation to celebration without a single wasted moment. The after-party shifted the energy entirely - warmer lighting, a live DJ, and a cocktail menu designed around the product's color palette. By midnight, the brand had three thousand social media mentions and a waitlist that crashed their server."]}
$json$::jsonb
WHERE slug = 'portfolio-new-beginnings';

UPDATE public.portfolio_projects SET story = $json$
{"paragraphs":["Thirty guests. One table. A menu built around the guest of honor. The brief was personal - a milestone birthday that needed to feel like a private club, not a party. The client wanted the evening to unfold like a conversation: slow, warm, and full of surprises that felt earned rather than staged.","We secured a private dining room in a restored colonial house, then redesigned the space entirely. A single mahogany table ran the length of the room, set for thirty with handmade ceramic plates, linen napkins, and a candle at every place setting. Overhead, a canopy of dried flowers and warm Edison bulbs created a ceiling of light that made the room feel like it existed outside of time.","The menu was designed in collaboration with the chef - seven courses, each one inspired by a memory the client had shared with us during planning. The third course was a dish from their childhood, recreated exactly. When it arrived, the table went quiet. That was the moment the evening stopped being an event and became something closer to a gift.","The room was lit almost entirely by candlelight, so the evening felt less like a dinner and more like a conversation that happened to include a meal. No speeches, no agenda, no timeline. Just thirty people, a long table, and the kind of warmth that only comes when every detail has been chosen with intention."]}
$json$::jsonb
WHERE slug = 'portfolio-intimate-celebration';

UPDATE public.portfolio_projects SET story = $json$
{"paragraphs":["We took the garden as the given and designed everything else to disappear into it. The venue was a private estate on the edge of Lagos, dense with palm trees, frangipani, and the kind of tropical greenery that makes any decoration feel redundant. Our approach was simple: enhance what was already there, and remove everything that competed with it.","Long communal tables stretched across the lawn, dressed in raw linen with scattered tropical leaves and low brass candleholders. String lights were woven through the trees at varying heights, creating a ceiling of warm light that moved gently in the evening breeze. The effect was of a room that had always been there - which is the hardest thing to design.","The live ensemble played from a stone terrace overlooking the garden, their sound carried by the natural acoustics of the space. Dinner was served family-style - large platters that moved down the table, encouraging strangers to pass plates and start conversations. By the second course, the rigid seating plan had dissolved into something more natural, which was exactly what we intended.","The evening moved from dinner into dancing without anyone noticing the transition. The band shifted their tempo, the lighting warmed, and the garden transformed from a dining room into a dance floor. We didn't announce the change - we let the guests discover it themselves, which made it feel like their idea rather than ours."]}
$json$::jsonb
WHERE slug = 'portfolio-garden-celebration';
