-- ── Additional seed data to fill out the website ──
-- Uses ON CONFLICT DO NOTHING so re-running is safe.

-- ── More portfolio projects ──
INSERT INTO public.portfolio_projects (title, slug, category, description, story, year, cover_image, cover_alt, gallery, published, sort_order) VALUES
  ('Kigali Rooftop Gala', 'portfolio-kigali-rooftop-gala', 'Corporate',
    'A black-tie corporate gala under the Kigali skyline.',
    '{"paragraphs":["The client wanted the city itself to be the backdrop. We stripped the rooftop to its bones and rebuilt it around a single idea: glass, gold, and the skyline as the third wall.","Two hundred guests arrived to a view they did not expect — and a room that made them forget it was there until the doors opened at midnight."]}'::jsonb,
    2025,
    'https://images.pexels.com/photos/14646752/pexels-photo-14646752.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Elegant rooftop gala with city views',
    '["https://images.pexels.com/photos/16935903/pexels-photo-16935903.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/29040997/pexels-photo-29040997.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    true, 6),
  ('Serena Lakeside Wedding', 'portfolio-serena-lakeside-wedding', 'Wedding',
    'A lakeside ceremony where the water carried the silence between vows.',
    '{"paragraphs":["We built the ceremony platform at the waterline so the lake became the aisle. By the time the sun dropped behind the hills, every guest had forgotten the rest of the world existed.","The reception moved indoors only when the stars made it impossible to stay outside — and even then, the doors stayed open."]}'::jsonb,
    2025,
    'https://images.pexels.com/photos/16120212/pexels-photo-16120212.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Beautiful lakeside wedding ceremony',
    '["https://images.pexels.com/photos/36873712/pexels-photo-36873712.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/16935999/pexels-photo-16935999.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    true, 7),
  ('Amahoro Stadium Concert', 'portfolio-amahoro-concert', 'Concert',
    'A sold-out stadium concert with a custom stage and full broadcast production.',
    '{"paragraphs":["Thirty thousand people. One stage. We handled the technical production end to end — staging, lighting, sound, LED walls, broadcast cameras, and the choreography that made the artist disappear into the music.","The moment the house lights dropped, the room became a single instrument."]}'::jsonb,
    2025,
    'https://images.pexels.com/photos/976862/pexels-photo-976862.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Large stadium concert with dramatic lighting',
    '["https://images.pexels.com/photos/24069/pexels-photo-24069.jpg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/14702256/pexels-photo-14702256.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    true, 8),
  ('The Garden City Launch', 'portfolio-garden-city-launch', 'Corporate',
    'A product launch that turned a shopping mall into a brand experience.',
    '{"paragraphs":["We took over the central atrium for seventy-two hours. By the time the doors opened, the space had been transformed into something the guests had never seen before — and the product sat at its center like it had always been there.","The reveal moment lasted four seconds. The conversation lasted weeks."]}'::jsonb,
    2025,
    'https://images.pexels.com/photos/167514/pexels-photo-167514.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Modern corporate product launch event',
    '["https://images.pexels.com/photos/2177813/pexels-photo-2177813.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/35880/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    true, 9),
  ('Mountain Lodge Retreat', 'portfolio-mountain-lodge-retreat', 'Private',
    'A three-day private retreat for forty guests in the Rwandan highlands.',
    '{"paragraphs":["The brief was disappear. We chose a lodge where the nearest neighbor was a hillside and the only schedule was sunrise to sunset.","Meals were served when the light was right. Conversations happened when the silence allowed. The weekend ended when the guests decided it should."]}'::jsonb,
    2024,
    'https://images.pexels.com/photos/6162805/pexels-photo-6162805.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Intimate mountain retreat with scenic views',
    '["https://images.pexels.com/photos/3937411/pexels-photo-3937411.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/1405528/pexels-photo-1405528.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    true, 10),
  ('Independence Day Festival', 'portfolio-independence-festival', 'Festival',
    'A national celebration with live performances, food vendors, and fireworks.',
    '{"paragraphs":["Forty thousand people came to celebrate. We built a festival that felt like a country introducing itself to itself — stages, food courts, art installations, and a closing fireworks display that lit up the entire valley.","The challenge was scale without losing intimacy. We solved it by designing five smaller experiences inside one large one."]}'::jsonb,
    2025,
    'https://images.pexels.com/photos/1533174072545-7a4b6ad7a6c3/pexels-photo-1533174072545-7a4b6ad7a6c3.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Large outdoor festival with crowds and stage',
    '["https://images.pexels.com/photos/1459749411175-04bf5292ceea/pexels-photo-1459749411175-04bf5292ceea.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/1501386761578-eac5c94b800a/pexels-photo-1501386761578-eac5c94b800a.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    true, 11)
ON CONFLICT (slug) DO NOTHING;

-- ── More events (completed) ──
INSERT INTO public.events (title, slug, description, category, event_date, location, cover_image, cover_alt, gallery, status, featured, published, sort_order) VALUES
  ('Kigali Rooftop Gala', 'kigali-rooftop-gala',
    'A black-tie corporate gala held on a private rooftop overlooking the Kigali skyline. Two hundred guests experienced an evening of fine dining, live jazz, and a sunset that turned the city gold.',
    'Corporate', '2025-11-15', 'Kigali, Rwanda',
    'https://images.pexels.com/photos/14646752/pexels-photo-14646752.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Elegant rooftop gala with city views',
    '["https://images.pexels.com/photos/16935903/pexels-photo-16935903.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/29040997/pexels-photo-29040997.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    'completed', false, true, 7),
  ('Serena Lakeside Wedding', 'serena-lakeside-wedding',
    'A lakeside ceremony at Serena Hotel where the water carried the silence between vows. The reception moved indoors only when the stars made it impossible to stay outside.',
    'Wedding', '2025-10-04', 'Lake Kivu, Rwanda',
    'https://images.pexels.com/photos/16120212/pexels-photo-16120212.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Beautiful lakeside wedding ceremony',
    '["https://images.pexels.com/photos/36873712/pexels-photo-36873712.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/16935999/pexels-photo-16935999.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    'completed', false, true, 8),
  ('Amahoro Stadium Concert', 'amahoro-stadium-concert',
    'A sold-out stadium concert with a custom stage, LED walls, and full broadcast production. Thirty thousand people and a single artist who became the music.',
    'Concert', '2025-08-20', 'Kigali, Rwanda',
    'https://images.pexels.com/photos/976862/pexels-photo-976862.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Large stadium concert with dramatic lighting',
    '["https://images.pexels.com/photos/24069/pexels-photo-24069.jpg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/14702256/pexels-photo-14702256.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    'completed', false, true, 9),
  ('Garden City Product Launch', 'garden-city-product-launch',
    'A product launch that transformed a shopping mall atrium into a brand experience. The reveal moment lasted four seconds. The conversation lasted weeks.',
    'Corporate', '2025-07-12', 'Kigali, Rwanda',
    'https://images.pexels.com/photos/167514/pexels-photo-167514.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Modern corporate product launch event',
    '["https://images.pexels.com/photos/2177813/pexels-photo-2177813.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/35880/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    'completed', false, true, 10),
  ('Mountain Lodge Retreat', 'mountain-lodge-retreat',
    'A three-day private retreat for forty guests in the Rwandan highlands. No schedule, no agenda — just silence, good food, and the kind of conversation that only happens when people have nowhere else to be.',
    'Private', '2025-06-08', 'Musanze, Rwanda',
    'https://images.pexels.com/photos/6162805/pexels-photo-6162805.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Intimate mountain retreat with scenic views',
    '["https://images.pexels.com/photos/3937411/pexels-photo-3937411.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/1405528/pexels-photo-1405528.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    'completed', false, true, 11),
  ('Independence Day Festival', 'independence-day-festival-2025',
    'A national celebration with live performances, food vendors, art installations, and a closing fireworks display that lit up the entire valley. Forty thousand people, five experiences, one night.',
    'Festival', '2025-07-04', 'Amahoro Stadium, Kigali',
    'https://images.pexels.com/photos/1533174072545-7a4b6ad7a6c3/pexels-photo-1533174072545-7a4b6ad7a6c3.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Large outdoor festival with crowds and stage',
    '["https://images.pexels.com/photos/1459749411175-04bf5292ceea/pexels-photo-1459749411175-04bf5292ceea.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/1501386761578-eac5c94b800a/pexels-photo-1501386761578-eac5c94b800a.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    'completed', false, true, 12),
  ('New Year Eve Countdown', 'new-year-eve-countdown-2025',
    'A rooftop countdown party with live DJs, premium cocktails, and a panoramic view of the city skyline as the clock struck midnight.',
    'Concert', '2024-12-31', 'Kigali, Rwanda',
    'https://images.pexels.com/photos/14702256/pexels-photo-14702256.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Rooftop party with DJ and city skyline',
    '["https://images.pexels.com/photos/24069/pexels-photo-24069.jpg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    'completed', false, true, 13),
  ('Charity Gala Dinner', 'charity-gala-dinner-2025',
    'A black-tie fundraiser raising over two hundred thousand dollars for education across Rwanda. Live auction, keynote speakers, and a room that gave before it left.',
    'Corporate', '2025-03-22', 'Radisson Blu, Kigali',
    'https://images.pexels.com/photos/1405528/pexels-photo-1405528.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Elegant charity gala dinner setup',
    '["https://images.pexels.com/photos/6162805/pexels-photo-6162805.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    'completed', false, true, 14)
ON CONFLICT (slug) DO NOTHING;

-- ── More events (upcoming) ──
INSERT INTO public.events (title, slug, description, category, event_date, location, cover_image, cover_alt, gallery, status, featured, published, sort_order) VALUES
  ('Kigali Fashion Week 2026', 'kigali-fashion-week-2026',
    'A week-long celebration of African fashion design featuring runway shows, pop-up markets, and industry talks from designers across the continent.',
    'Festival', '2026-11-18', 'Kigali Arena, Rwanda',
    'https://images.pexels.com/photos/1558618666-fcd25c85f82e/pexels-photo-1558618666-fcd25c85f82e.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Fashion runway show with models',
    '[]'::jsonb,
    'upcoming', false, true, 15),
  ('Tech Innovation Summit', 'tech-innovation-summit-2026',
    'Where founders, investors, and technologists shape the future of African tech. Two days of keynotes, workshops, and networking.',
    'Corporate', '2026-08-14', 'Kigali Convention Centre',
    'https://images.pexels.com/photos/2608516/pexels-photo-2608516.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Modern conference hall with attendees',
    '[]'::jsonb,
    'upcoming', false, true, 16),
  ('Sunset Jazz Evening', 'sunset-jazz-evening-2026',
    'An intimate evening of smooth jazz and curated wine selections as the sun sets over Lake Kivu.',
    'Private', '2026-10-10', 'Marriott Hotel, Kigali',
    'https://images.pexels.com/photos/1415201364774-f6f0bb35f28f/pexels-photo-1415201364774-f6f0bb35f28f.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'Jazz performance with wine glasses',
    '[]'::jsonb,
    'upcoming', false, true, 17)
ON CONFLICT (slug) DO NOTHING;

-- ── More testimonials ──
INSERT INTO public.testimonials (client_name, quote, event_type, location, published, sort_order) VALUES
  ('Jean-Pierre M.', 'Fiesta turned our product launch into the most talked-about event in Kigali that quarter. The production quality was beyond what we imagined possible.', 'Corporate', 'Kigali', true, 5),
  ('Grace & Emmanuel N.', 'Every detail was a reflection of us. They did not just plan our wedding — they understood who we are and built the evening around that understanding.', 'Wedding', 'Kigali', true, 6),
  ('Fatima A.', 'The charity gala raised more than we expected, and that was because the room felt something. Fiesta does not decorate spaces — they create emotions.', 'Corporate', 'Nairobi', true, 7),
  ('Samuel O.', 'We have worked with event companies across three countries. Fiesta is the only one that made us feel like we were their only client. The attention to detail was extraordinary.', 'Corporate', 'Lagos', true, 8),
  ('Claire & James H.', 'Our destination wedding in Rwanda was flawless. Every logistical challenge was handled before we even knew it existed. All we had to do was show up and be married.', 'Wedding', 'Musanze', true, 9)
ON CONFLICT DO NOTHING;
